### ISSUE TITLE
Ability to view an existing certificate

### ISSUE THREAD

**Issue by mrry550** [RHInception/cacophony#1]
As user who generated cert: add functionality to be able to view an existing certificate (or regenerate the key) 

As admin who is maintaining server: add functionality to be able to view any certificates

**Comment by ashcrow** [comment]
I've spun the second item into #3.

**Comment by mrry550** [comment]
Comment from miwhite "is there a way to force regeneration of the certificate?"

**Comment by ashcrow** [comment]
@mrry550 In regards to Mr. White's comment I believe that is what @themurph is describing with #2.

**Comment by mrry550** [comment]
To clarify, this is specifically to view a detailed certificate already generated. And could apply to both the user and the admin roles.

**Comment by ashcrow** [comment]
:+1: understood
