### ISSUE TITLE
Gratuitous use of marketing speak detected

### ISSUE THREAD

**Issue by timlnx** [RHInception/cacophony#10]
Please stop using the term **automagic**.

To quote [Urban Dictionary](http://www.urbandictionary.com/define.php?term=Automagic&defid=3409264):

```
Marketing speak to make an already uncomplicated user input / automated
process seem like something more than it is
```

Respectfully,

-- Tim 'Automatic' Bielawa

**Comment by mrry550** [comment]
![image](https://f.cloud.github.com/assets/6107104/2518048/b3e9c65c-b45f-11e3-86d9-50d6b993a647.png)

**Comment by ashcrow** [comment]
![image](http://memedad.com/memes/149945.jpg)

**Comment by themurph** [comment]
![manopticon_surveillance_drone](https://f.cloud.github.com/assets/1348919/2526831/4ca2f42e-b4fe-11e3-80be-943e480b6b9f.gif)
Is it automatic @tbielawa ??? Is it really....
